// Mapeamento de relacionamentos entre artigos e nutrientes
// Atualizado em 20/05/2026 - Cobertura completa de 95 artigos

export const artigoToNutrientes: Record<string, string[]> = {
  '5-suplementos-mais-vendidos': ['creatina', 'proteina', 'omega-3', 'vitamina-d'],
  'acido-folico-b9-gestantes-gravidez': ['acido-folico', 'ferro', 'vitamina-b12'],
  'ashwagandha-estresse-ansiedade-cortisol': ['magnesio', 'vitamina-b6'],
  'bcaa-aminoacidos-massa-muscular-funciona': ['bcaa', 'proteina', 'creatina'],
  'biotina-cabelo-unhas-dose-funciona': ['vitamina-b7', 'zinco', 'vitamina-c'],
  'bulking-calorias-superavit': ['proteina', 'creatina', 'bcaa'],
  'cafeina-performance-dose-pre-treino': ['creatina'],
  'calcio-ossos-osteoporose-qual-tomar': ['calcio', 'vitamina-d', 'vitamina-k2', 'magnesio'],
  'calculadora-nutricional-calorias-macros': ['proteina'],
  'calcular-proteina-por-peso': ['proteina'],
  'calorias-manutencao-encontrar': ['proteina'],
  'coenzima-q10-coq10-energia-coracao': ['coenzima-q10', 'magnesio', 'omega-3'],
  'colageno-hidrolisado-funciona-pele-articulacoes': ['colageno', 'vitamina-c', 'vitamina-b7'],
  'como-calcular-gasto-calorico-tmb-tdee': ['proteina'],
  'como-dividir-macros-cutting-bulking-manutencao': ['proteina', 'creatina'],
  'como-dormir-melhor-suplementos': ['magnesio', 'vitamina-d'],
  'como-fortalecer-imunidade-suplementos': ['vitamina-c', 'vitamina-d', 'zinco', 'omega-3', 'proteina'],
  'contador-de-calorias-online-gratis': ['proteina'],
  'creatina-antes-ou-depois-treino': ['creatina', 'proteina'],
  'creatina-beneficios-efeitos-colaterais-dosagem-2026': ['creatina'],
  'creatina-como-tomar': ['creatina', 'proteina'],
  'creatina-e-cafe': ['creatina'],
  'creatina-engorda': ['creatina'],
  'creatina-fase-carga-necessaria': ['creatina'],
  'creatina-faz-mal': ['creatina'],
  'creatina-guia-completo-ganho-muscular': ['creatina', 'proteina'],
  'creatina-monohidratada-vs-outras': ['creatina'],
  'creatina-para-idosos': ['creatina', 'vitamina-d', 'proteina'],
  'creatina-para-mulheres': ['creatina', 'proteina'],
  'creatina-para-que-serve': ['creatina'],
  'creatina-quem-nao-deve-tomar': ['creatina'],
  'creatina-retencao-liquido': ['creatina'],
  'curcuma-curcumina-inflamacao-articulacoes': ['omega-3', 'vitamina-d'],
  'cutting-modelo-calorias-macros': ['proteina', 'creatina', 'bcaa'],
  'deficit-calorico-quanto-cortar': ['proteina', 'l-carnitina'],
  'dieta-reversa-como-fazer': ['proteina'],
  'diferenca-proteinas-whey-caseina-albumina': ['proteina', 'caseina', 'albumina'],
  'economizar-300-reais-suplementacao': ['creatina', 'proteina'],
  'erros-contagem-calorias': ['proteina'],
  'ferro-anemia-deficiencia-tratamento': ['ferro', 'vitamina-c', 'vitamina-b12'],
  'formula-mifflin-st-jeor-homem': ['proteina'],
  'glucosamina-condroitina-articulacoes-artrite': ['glucosamina', 'colageno', 'vitamina-c'],
  'guia-completo-creatina-2026': ['creatina', 'proteina', 'vitamina-d'],
  'guia-whey-protein-2026': ['proteina', 'creatina', 'bcaa'],
  'imc-o-que-significa-como-calcular': ['proteina'],
  'iodo-tireoide-hipotireoidismo-dose': ['iodo', 'selenio', 'zinco'],
  'l-carnitina-queima-gordura-performance': ['l-carnitina', 'creatina'],
  'maca-peruana-libido-energia-hormonios': ['zinco', 'vitamina-d'],
  'macros-cutting-como-calcular': ['proteina', 'creatina'],
  'macros-para-definicao-muscular': ['proteina', 'creatina', 'l-carnitina'],
  'macros-para-ganho-massa': ['proteina', 'creatina', 'bcaa'],
  'magnesio-ansiedade-sono-tipos': ['magnesio', 'vitamina-b6', 'vitamina-d'],
  'melatonina-sono-insonia-dose-ideal': ['magnesio', 'vitamina-b6'],
  'melhor-marca-creatina-brasil': ['creatina'],
  'melhores-marcas-whey-protein-2026': ['proteina', 'creatina'],
  'mifflin-st-jeor-formula': [],
  'monjaro-diabetes-tipo-2-funciona-melhor-insulina': ['cromo'],
  'monjaro-efeitos-colaterais-o-que-esperar': [],
  'monjaro-emagrece-quantos-quilos-resultados-reais': [],
  'monjaro-preco-quanto-custa-como-economizar-2026': [],
  'monjaro-tirzepatida-guia-completo-emagrecimento': [],
  'monjaro-vs-ozempic-qual-emagrece-mais-comparacao': [],
  'neat-fator-oculto-dieta': ['proteina', 'l-carnitina'],
  'o-que-e-tdee-como-calcular': ['proteina'],
  'omega-3-beneficios-comprovados': ['omega-3', 'vitamina-d', 'vitamina-e'],
  'plateau-dieta-como-sair': ['proteina', 'l-carnitina'],
  'pre-treino-vale-a-pena': ['creatina'],
  'probioticos-intestino-flora-intestinal': ['probioticos', 'vitamina-d', 'zinco'],
  'proteina-isolada-soja-veganos': ['proteina', 'vitamina-b12'],
  'proteina-por-dia-quanto-consumir-guia-completo': ['proteina', 'creatina', 'bcaa'],
  'quanta-agua-beber-por-dia-calculo-por-peso': [],
  'quantas-calorias-comer-por-dia': ['proteina'],
  'receitas-whey-protein-faceis': ['proteina'],
  'refeed-day-como-fazer': [],
  'selenio-tireoide-imunidade-antioxidante': ['selenio', 'iodo', 'vitamina-e'],
  'spirulina-superalimento-proteina-vegana': ['vitamina-b12', 'ferro'],
  'suplementos-para-dor-articulacao-joelho': ['glucosamina', 'colageno', 'omega-3', 'vitamina-d'],
  'suplementos-para-emagrecer-funcionam': ['proteina', 'creatina', 'l-carnitina', 'omega-3'],
  'suplementos-para-iniciantes': ['creatina', 'proteina', 'omega-3', 'vitamina-d'],
  'tribulus-terrestris-testosterona-libido': ['zinco'],
  'vitamina-a-retinol-visao-pele-imunidade': ['vitamina-a', 'vitamina-d', 'zinco'],
  'vitamina-b12-vegetarianos-veganos': ['vitamina-b12', 'ferro', 'acido-folico'],
  'vitamina-c-imunidade-gripes-resfriados': ['vitamina-c', 'zinco', 'vitamina-d'],
  'vitamina-d-deficiencia-brasileiros': ['vitamina-d', 'calcio', 'magnesio'],
  'vitamina-d3-k2-juntas-beneficios': ['vitamina-d', 'vitamina-k2', 'calcio', 'magnesio'],
  'vitamina-e-antioxidante-pele-fertilidade': ['vitamina-e', 'vitamina-c', 'selenio'],
  'vitamina-k2-d3-calcio-ossos-coracao': ['vitamina-k2', 'vitamina-d', 'calcio'],
  'whey-antes-ou-depois-treino': ['proteina', 'creatina'],
  'whey-com-leite-ou-agua': ['proteina'],
  'whey-engorda-ou-emagrece': ['proteina'],
  'whey-isolado-para-que-serve': ['proteina', 'creatina'],
  'whey-isolado-vs-concentrado': ['proteina', 'creatina', 'bcaa'],
  'whey-protein-intolerantes-lactose': ['proteina'],
  'zinco-imunidade-testosterona-pele': ['zinco', 'selenio', 'vitamina-d'],
  'zma-zinco-magnesio-b6-sono-testosterona': ['zinco', 'magnesio', 'vitamina-b6'],
}

export const nutrienteToArtigos: Record<string, string[]> = {
  'acido-folico': ['vitamina-b12-vegetarianos-veganos', 'acido-folico-b9-gestantes-gravidez'],
  'albumina': ['diferenca-proteinas-whey-caseina-albumina'],
  'bcaa': ['bcaa-aminoacidos-massa-muscular-funciona', 'whey-isolado-vs-concentrado', 'proteina-por-dia-quanto-consumir-guia-completo', 'cutting-modelo-calorias-macros', 'bulking-calorias-superavit'],
  'calcio': ['vitamina-d-deficiencia-brasileiros', 'calcio-ossos-osteoporose-qual-tomar', 'vitamina-k2-d3-calcio-ossos-coracao', 'vitamina-d3-k2-juntas-beneficios'],
  'caseina': ['diferenca-proteinas-whey-caseina-albumina'],
  'coenzima-q10': ['coenzima-q10-coq10-energia-coracao'],
  'colageno': ['colageno-hidrolisado-funciona-pele-articulacoes', 'glucosamina-condroitina-articulacoes-artrite', 'suplementos-para-dor-articulacao-joelho'],
  'creatina': ['guia-completo-creatina-2026', 'bcaa-aminoacidos-massa-muscular-funciona', 'l-carnitina-queima-gordura-performance', 'cafeina-performance-dose-pre-treino', 'pre-treino-vale-a-pena'],
  'cromo': ['monjaro-diabetes-tipo-2-funciona-melhor-insulina'],
  'ferro': ['vitamina-b12-vegetarianos-veganos', 'ferro-anemia-deficiencia-tratamento', 'spirulina-superalimento-proteina-vegana', 'acido-folico-b9-gestantes-gravidez'],
  'glucosamina': ['glucosamina-condroitina-articulacoes-artrite', 'suplementos-para-dor-articulacao-joelho'],
  'iodo': ['iodo-tireoide-hipotireoidismo-dose', 'selenio-tireoide-imunidade-antioxidante'],
  'l-carnitina': ['l-carnitina-queima-gordura-performance', 'deficit-calorico-quanto-cortar', 'neat-fator-oculto-dieta', 'macros-para-definicao-muscular', 'suplementos-para-emagrecer-funcionam'],
  'magnesio': ['vitamina-d-deficiencia-brasileiros', 'magnesio-ansiedade-sono-tipos', 'calcio-ossos-osteoporose-qual-tomar', 'ashwagandha-estresse-ansiedade-cortisol', 'melatonina-sono-insonia-dose-ideal'],
  'omega-3': ['omega-3-beneficios-comprovados', 'curcuma-curcumina-inflamacao-articulacoes', 'coenzima-q10-coq10-energia-coracao', 'suplementos-para-emagrecer-funcionam', 'como-fortalecer-imunidade-suplementos'],
  'probioticos': ['probioticos-intestino-flora-intestinal'],
  'proteina': ['guia-completo-creatina-2026', 'bcaa-aminoacidos-massa-muscular-funciona', 'creatina-guia-completo-ganho-muscular', 'whey-isolado-vs-concentrado', 'whey-isolado-para-que-serve'],
  'selenio': ['zinco-imunidade-testosterona-pele', 'iodo-tireoide-hipotireoidismo-dose', 'selenio-tireoide-imunidade-antioxidante', 'vitamina-e-antioxidante-pele-fertilidade'],
  'vitamina-a': ['vitamina-a-retinol-visao-pele-imunidade'],
  'vitamina-b12': ['vitamina-b12-vegetarianos-veganos', 'ferro-anemia-deficiencia-tratamento', 'spirulina-superalimento-proteina-vegana', 'acido-folico-b9-gestantes-gravidez', 'proteina-isolada-soja-veganos'],
  'vitamina-b6': ['magnesio-ansiedade-sono-tipos', 'ashwagandha-estresse-ansiedade-cortisol', 'melatonina-sono-insonia-dose-ideal', 'zma-zinco-magnesio-b6-sono-testosterona'],
  'vitamina-b7': ['colageno-hidrolisado-funciona-pele-articulacoes', 'biotina-cabelo-unhas-dose-funciona'],
  'vitamina-c': ['ferro-anemia-deficiencia-tratamento', 'colageno-hidrolisado-funciona-pele-articulacoes', 'vitamina-c-imunidade-gripes-resfriados', 'biotina-cabelo-unhas-dose-funciona', 'vitamina-e-antioxidante-pele-fertilidade'],
  'vitamina-d': ['vitamina-d-deficiencia-brasileiros', 'omega-3-beneficios-comprovados', 'zinco-imunidade-testosterona-pele', 'magnesio-ansiedade-sono-tipos', 'guia-completo-creatina-2026'],
  'vitamina-e': ['omega-3-beneficios-comprovados', 'selenio-tireoide-imunidade-antioxidante', 'vitamina-e-antioxidante-pele-fertilidade'],
  'vitamina-k2': ['calcio-ossos-osteoporose-qual-tomar', 'vitamina-k2-d3-calcio-ossos-coracao', 'vitamina-d3-k2-juntas-beneficios'],
  'zinco': ['zinco-imunidade-testosterona-pele', 'vitamina-c-imunidade-gripes-resfriados', 'biotina-cabelo-unhas-dose-funciona', 'probioticos-intestino-flora-intestinal', 'iodo-tireoide-hipotireoidismo-dose'],
}

export function getNutrientesRelacionados(artigoSlug: string): string[] {
  return artigoToNutrientes[artigoSlug] || []
}

export function getArtigosRelacionados(nutrienteSlug: string): string[] {
  return nutrienteToArtigos[nutrienteSlug] || []
}
